const MEANING_OVERRIDES: Record<string, string> = {
  "sie": "她；他们/她们/它们；您（敬称）",
  "es": "它；这件事；用作无人称主语",
  "das": "这；那；这个/那个（中性冠词或代词）",
  "nicht": "不；没有；并非；不是",
  "die": "这；那；这些/那些（阴性或复数冠词/代词）",
  "der": "这；那；这个/那个（阳性冠词或代词）",
  "ein": "一；一个；某个；开启的",
  "in": "在……里面；进入；在……期间；时髦的",
  "ja": "是；对；当然；毕竟（语气词）",
  "aber": "但是；可是；却；真是（加强语气）",
  "wenn": "如果；当……时；每当",
  "ihr": "你们；她的；他们/她们的；她（第三格）",
  "da": "那里；这时；因为；既然",
  "kann": "能；会；可以；可能",
  "gut": "好的；很好地；善；财产/货物（das Gut）",
  "auch": "也；同样；甚至；的确",
  "hier": "这里；在此；此时",
  "was": "什么；某事；……的东西",
  "zu": "到；向；在……处；太；关闭的",
  "auf": "在……上；到……上；打开的",
  "an": "在……旁；向；接通的；从事于",
  "mit": "和；与；带着；用",
  "von": "从；来自；……的；由",
  "nach": "向；在……之后；按照",
  "über": "在……上方；关于；超过；通过",
  "vor": "在……前；在……之前；由于",
  "aus": "从……出来；来自；由……制成",
  "bei": "在……处；在……期间；就……而言",
  "um": "围绕；在……点钟；为了；大约",
  "für": "为了；给；对于；持续（时间）",
  "als": "作为；比；当……时",
  "wie": "怎样；像；如同；多么",
  "so": "这样；如此；那么；大约",
  "doch": "可是；毕竟；还是；确实（语气词）",
  "schon": "已经；早就；确实；还算",
  "noch": "还；仍然；另外；更",
  "nur": "只；仅仅；不过",
  "also": "所以；那么；也就是说",
  "gerade": "正好；刚刚；笔直的；偶数的",
  "wieder": "又；再次；返回",
  "einmal": "一次；曾经；有一天",
  "machen": "做；制作；使得；进行",
  "haben": "有；拥有；经历；必须（zu haben）",
  "sein": "是；存在；在；他的/它的（物主词）",
  "werden": "变成；成为；将要；被（构成被动态）",
  "wissen": "知道；了解；懂得",
  "sprechen": "说；讲话；交谈；会说某种语言",
  "gehen": "走；去；运转；可行",
  "kommen": "来；到达；发生；进入某种状态",
  "nehmen": "拿；取；乘坐；接受；花费（时间）",
  "geben": "给；提供；有/存在（es gibt）",
  "stehen": "站立；位于；写着；适合",
  "liegen": "躺；位于；在于",
  "fahren": "行驶；乘车；驾驶",
  "bringen": "带来；拿来；导致",
  "halten": "拿住；停下；认为；遵守",
  "ziehen": "拉；搬家；吸引；抽取",
  "lassen": "让；留下；停止；使某事被做",
  "finden": "找到；发现；认为",
  "sehen": "看见；理解；会面",
  "laufen": "跑；步行；运转；播放",
  "rufen": "喊；呼叫；打电话；召集",
  "setzen": "放置；使坐下；设定；押注",
  "sitzen": "坐；位于；合身；被监禁",
  "tragen": "携带；穿戴；承担；支撑",
  "treffen": "遇见；击中；作出（决定）",
  "passen": "合适；合身；配合；传球",
  "fehlen": "缺少；不在；想念；出错",
  "lernen": "学习；学会；得知",
  "heißen": "叫作；意味着；命令",
  "sollen": "应该；据说；奉命",
  "müssen": "必须；不得不；一定是",
  "dürfen": "可以；被允许；大概",
  "mögen": "喜欢；可能；想要（möchte）",
  "kosten": "花费；价钱为；品尝",
  "schließen": "关闭；锁上；结束；推断",
  "öffnen": "打开；开放；开通",
  "aufhalten": "阻拦；耽搁；逗留；撑开",
  "aufheben": "捡起；保存；取消；举起",
  "einstellen": "设置；雇用；停止；调节",
  "vorstellen": "介绍；想象；展示",
  "ausfallen": "取消；发生故障；脱落；结果是",
  "übernehmen": "接管；承担；采用；抄录",
  "übersetzen": "翻译；把……运到对岸",
  "umgehen": "绕开；处理；与……交往",
  "bestimmen": "决定；规定；确定；指定",
  "erkennen": "认出；认识到；判定",
  "entwickeln": "发展；开发；形成；冲洗照片",
  "vermitteln": "传授；调解；介绍；促成",
  "vertreten": "代表；代理；主张；代课",
  "beziehen": "取得；涉及；订阅；搬入",
  "eingehen": "进入；收到；答应；枯萎",
  "ausgehen": "外出；熄灭；用尽；假定",
  "vorliegen": "存在；摆在面前；已提交",
  "der Stock": "楼层；棍子；库存",
  "die Farbe": "颜色；颜料；色彩",
  "der Zug": "火车；拉力；一口/一吸；特征",
  "das Schloss": "锁；城堡；宫殿",
  "die Bank": "银行；长椅",
  "das Blatt": "叶子；纸张；报纸；牌",
  "die Karte": "卡片；地图；票；菜单",
  "das Gericht": "法院；判决；菜肴",
  "das Fach": "格子；学科；专业领域",
  "die Stimme": "声音；嗓音；选票；意见",
  "die Mutter": "母亲；螺母；母体",
  "der Leiter": "负责人；梯子；导体",
  "der Schlüssel": "钥匙；关键；编码",
  "der See": "湖；湖泊",
  "die See": "海；海洋",
  "die Stelle": "位置；职位；地方；部位",
  "der Satz": "句子；组/套；跳跃；定理",
  "der Fall": "情况；案件；坠落；语法格",
  "der Lauf": "奔跑；过程；枪管；水流",
  "der Raum": "房间；空间；余地；地区",
  "der Grund": "原因；地面；基础；底部",
  "das Mittel": "手段；方法；药剂；中间",
  "die Art": "种类；方式；物种；性格",
  "die Aufgabe": "任务；练习题；放弃；托运",
  "der Absatz": "段落；鞋跟；台阶；销量",
  "die Aufnahme": "录音/录像；接收；录取；照片",
  "die Leitung": "领导；管理；线路；管道",
  "der Betrieb": "企业；运行；营业；忙乱",
  "die Richtung": "方向；路线；倾向；流派",
  "die Vorstellung": "介绍；想象；观念；演出",
  "die Verbindung": "连接；联系；交通班次；化合物",
  "die Leistung": "成绩；表现；功率；给付",
  "die Haltung": "姿势；态度；饲养；支撑",
  "die Anlage": "设备；设施；投资；附件；天赋",
  "der Beitrag": "文章；贡献；会费；节目",
  "der Auftrag": "任务；委托；订单；涂层",
  "der Anspruch": "要求；权利；标准；期望",
  "der Zustand": "状态；状况；情形",
  "die Ausgabe": "支出；版本；发放；输出",
  "die Angabe": "说明；信息；数据；陈述",
  "die Folge": "后果；顺序；一集；系列",
  "der Wert": "价值；数值；重要性",
  "das Verhältnis": "关系；比例；状况；恋爱关系",
  "die Fläche": "表面；面积；区域；平面",
  "der Bereich": "范围；领域；区域",
  "die Erfahrung": "经验；经历；体验",
  "der Punkt": "点；要点；分数；时刻",
  "der Eindruck": "印象；压痕；效果",
  "der Umgang": "交往；处理方式；使用",
  "die Rate": "分期付款；比率；速率",
  "die Untersuchung": "检查；调查；研究",
  "die Deckung": "掩护；覆盖；资金保障",
  "erreichen": "到达；达到；联系到",
  "lenken": "驾驶；引导；转移（注意力）",
  "regieren": "统治；执政；支配",
  "angeordnet": "排列的；下令的；规定的",
  "abgeschlossen": "关闭的；完成的；封闭的",
  "angewiesen": "依赖的；被指示的",
  "lahm": "瘸的；迟缓的；乏味的",
  "der Untergang": "沉没；衰亡；没落",
  "die Branche": "行业；分支",
  "die Suite": "套房；组曲；软件套件",
  "der Vorsitzender": "主席；负责人",
  "der Rohstoff": "原料；自然资源",
  "die Rezension": "评论；书评；影评",
  "die Emission": "排放；发行；发射",
  "die Wette": "赌约；打赌",
  "der Befehl": "命令；指令",
  "die Akademie": "学院；研究院；学会",
  "das Institut": "机构；研究所；学院",
  "das Extra": "额外内容；附加项目；临时演员",
  "der Alarm": "警报；警觉；惊慌",
  "landen": "着陆；登陆；最终到达",
  "rücken": "移动；挪动；靠近",
  "der Rücken": "背；背部；后面",
  "die Ehre": "荣誉；尊敬；荣幸",
  "vielfältig": "多样的；丰富的；多方面的",
  "die Süße": "甜味；甜度；甜食",
  "fasziniert": "着迷的；被吸引的",
  "der Barkeeper": "酒吧调酒师；酒保",
  "der Fritz": "弗里茨（德语男子名）",
  "die Freundschaft": "友谊；友情；友好关系",
  "der Bastard": "私生子；杂种；混合品种",
  "die Schnauze": "口鼻部；动物的嘴；粗鲁的嘴",
};

export function expandedMeaning(term: string, fallback: string) {
  return MEANING_OVERRIDES[term.trim()] ?? fallback;
}

export const expandedMeaningCount = Object.keys(MEANING_OVERRIDES).length;
