export type WordbookEntry = {
  id: string;
  level: "A1" | "A2";
  term: string;
  forms: string;
  type: string;
  meaning: string;
  example: string;
  exampleZh: string;
  grammarTitle: string;
  grammar: string;
  memory: string;
  storyDe: string;
  storyZh: string;
};

export const A1_WORDS = [
  {
    id: "a1-aufstehen",
    level: "A1",
    term: "aufstehen",
    forms: "trennbar · steht auf · stand auf · ist aufgestanden",
    type: "Verb",
    meaning: "起床；站起来",
    example: "Ich stehe jeden Morgen um sieben Uhr auf.",
    exampleZh: "我每天早上七点起床。",
    grammarTitle: "可分前缀 auf-",
    grammar:
      "在陈述句中，变位后的 stehen 放在第二位，auf 放到句末。表示起床时，完成时使用 sein：ist aufgestanden。",
    memory: "stehen 是“站”，auf 是“向上”——向上站起来，就是起床。",
    storyDe: "Um sieben Uhr steht Mia auf.",
    storyZh: "七点，米娅起床了。",
  },
  {
    id: "a1-fruehstuecken",
    level: "A1",
    term: "frühstücken",
    forms: "frühstückt · frühstückte · hat gefrühstückt",
    type: "Verb",
    meaning: "吃早餐",
    example: "Wir frühstücken am Sonntag zusammen.",
    exampleZh: "星期天我们一起吃早餐。",
    grammarTitle: "通常不需要宾语",
    grammar:
      "frühstücken 本身已包含“吃早餐”的意思，可以直接与时间、地点或方式成分连用。",
    memory: "früh 是“早”，Frühstück 是“早餐”，加 -en 就成为“吃早餐”。",
    storyDe: "Danach frühstückt sie in der Küche.",
    storyZh: "之后，她在厨房吃早餐。",
  },
  {
    id: "a1-familie",
    level: "A1",
    term: "die Familie",
    forms: "die Familie · die Familien",
    type: "Nomen",
    meaning: "家庭；家人",
    example: "Meine Familie wohnt in Köln.",
    exampleZh: "我的家人住在科隆。",
    grammarTitle: "阴性名词",
    grammar:
      "Familie 使用冠词 die，复数为 Familien。把一家人看作一个整体作主语时，动词通常使用第三人称单数。",
    memory: "Familie 与英语 family 发音相近。",
    storyDe: "Ihre Familie sitzt schon am Tisch.",
    storyZh: "她的家人已经坐在餐桌旁了。",
  },
  {
    id: "a1-arbeiten",
    level: "A1",
    term: "arbeiten",
    forms: "arbeitet · arbeitete · hat gearbeitet",
    type: "Verb",
    meaning: "工作",
    example: "Ich arbeite als Verkäuferin in Berlin.",
    exampleZh: "我在柏林做售货员。",
    grammarTitle: "描述职业与工作地点",
    grammar:
      "als 后接职业，通常不加冠词；bei 后接雇主，in 后接工作地点。词干以 -t 结尾，因此 du arbeitest、er arbeitet 中会增加一个 e。",
    memory: "Arbeit 是“工作”，arbeiten 是“工作、劳动”。",
    storyDe: "Um acht Uhr fährt Mia zur Arbeit.",
    storyZh: "八点，米娅去上班。",
  },
  {
    id: "a1-brauchen",
    level: "A1",
    term: "brauchen",
    forms: "braucht · brauchte · hat gebraucht",
    type: "Verb",
    meaning: "需要",
    example: "Ich brauche heute einen Regenschirm.",
    exampleZh: "我今天需要一把雨伞。",
    grammarTitle: "后接第四格",
    grammar:
      "需要的人作主语，需要的事物作第四格宾语：Ich brauche einen Stift。",
    memory: "把 brauchen 和“必需品”联系起来：需要什么，就把什么放在第四格里。",
    storyDe: "Für den Tag braucht sie ihren Laptop und ein Heft.",
    storyZh: "这一天她需要带上笔记本电脑和一个本子。",
  },
  {
    id: "a1-einkaufen",
    level: "A1",
    term: "einkaufen",
    forms: "trennbar · kauft ein · kaufte ein · hat eingekauft",
    type: "Verb",
    meaning: "购物；采购",
    example: "Am Freitag kaufe ich Gemüse auf dem Markt ein.",
    exampleZh: "星期五我在市场买蔬菜。",
    grammarTitle: "可分动词",
    grammar:
      "陈述句中 ein 放到句末：Ich kaufe ein。若说明购买的东西，可直接接第四格宾语。",
    memory: "kaufen 是“买”，ein- 有“买进来”的感觉。",
    storyDe: "In der Mittagspause kauft sie Brot und Äpfel ein.",
    storyZh: "午休时，她买了面包和苹果。",
  },
  {
    id: "a1-gern",
    level: "A1",
    term: "gern",
    forms: "gern · lieber · am liebsten",
    type: "Adverb",
    meaning: "乐意地；喜欢",
    example: "Ich höre gern deutsche Musik.",
    exampleZh: "我喜欢听德国音乐。",
    grammarTitle: "表达喜欢做某事",
    grammar:
      "gern 修饰一个动作，通常放在变位动词之后。比较级为 lieber，最高级为 am liebsten。",
    memory: "gern 不等于“喜欢某件东西”，而是“喜欢做这个动作”。",
    storyDe: "Nach der Arbeit geht sie gern im Park spazieren.",
    storyZh: "下班后，她喜欢在公园散步。",
  },
  {
    id: "a1-verstehen",
    level: "A1",
    term: "verstehen",
    forms: "versteht · verstand · hat verstanden",
    type: "Verb",
    meaning: "理解；听懂",
    example: "Entschuldigung, ich verstehe das Wort nicht.",
    exampleZh: "对不起，我不明白这个词。",
    grammarTitle: "后接第四格",
    grammar:
      "被理解的人、语言或内容使用第四格。ver- 在这里不可分，完成时是 verstanden，不再加 ge-。",
    memory: "听到一句话后能“站在它下面看清结构”，就是 verstehen。",
    storyDe: "Dort versteht sie eine Nachricht ihrer Freundin nicht.",
    storyZh: "在那里，她没看懂朋友发来的一条消息。",
  },
  {
    id: "a1-frage",
    level: "A1",
    term: "die Frage",
    forms: "die Frage · die Fragen",
    type: "Nomen",
    meaning: "问题；提问",
    example: "Darf ich eine Frage stellen?",
    exampleZh: "我可以问一个问题吗？",
    grammarTitle: "固定搭配 eine Frage stellen",
    grammar:
      "德语通常说 eine Frage stellen，直译为“提出一个问题”；Frage 是阴性名词，复数加 -n。",
    memory: "fragen 是“询问”，去掉词尾 -n 就得到名词 Frage。",
    storyDe: "Deshalb schreibt sie ihrer Freundin eine Frage.",
    storyZh: "因此，她给朋友写了一个问题。",
  },
  {
    id: "a1-muede",
    level: "A1",
    term: "müde",
    forms: "müde · müder · am müdesten",
    type: "Adjektiv",
    meaning: "疲倦的；困的",
    example: "Nach dem Deutschkurs bin ich müde.",
    exampleZh: "德语课后我很累。",
    grammarTitle: "与 sein 连用时不变词尾",
    grammar:
      "形容词放在 sein、werden、bleiben 后作表语时，不需要添加词尾：Ich bin müde。",
    memory: "把 ü 想成一双快要闭上的眼睛。",
    storyDe: "Am Abend ist Mia müde, aber zufrieden.",
    storyZh: "晚上，米娅很累，但很满足。",
  },
  {
    id: "a1-wohnen",
    level: "A1",
    term: "wohnen",
    forms: "wohnt · wohnte · hat gewohnt",
    type: "Verb",
    meaning: "居住；住在",
    example: "Ich wohne mit meiner Schwester in Bonn.",
    exampleZh: "我和姐姐住在波恩。",
    grammarTitle: "居住地点使用 in",
    grammar:
      "表示“住在某地”时常使用 in。地点没有方向变化，因此带冠词的地点通常使用第三格。",
    memory: "Wohnung 是“住宅”，wohnen 就是在住宅里居住。",
    storyDe:
      "Am nächsten Morgen beginnt ein neuer Tag. Mia wohnt mit ihrer Familie in einer kleinen Wohnung.",
    storyZh: "第二天早上，新的一天开始了。米娅和家人住在一套小公寓里。",
  },
  {
    id: "a1-zimmer",
    level: "A1",
    term: "das Zimmer",
    forms: "das Zimmer · die Zimmer",
    type: "Nomen",
    meaning: "房间",
    example: "Mein Zimmer hat ein großes Fenster.",
    exampleZh: "我的房间有一扇大窗户。",
    grammarTitle: "单复数形式相同",
    grammar:
      "Zimmer 是中性名词，使用 das。它的复数仍写作 Zimmer，只能通过冠词 das 或 die 判断单复数。",
    memory: "在酒店看到 Zimmer，就可以想到“房间”。",
    storyDe: "Ihr Zimmer ist klein, aber hell und ruhig.",
    storyZh: "她的房间不大，但明亮又安静。",
  },
  {
    id: "a1-trinken",
    level: "A1",
    term: "trinken",
    forms: "trinkt · trank · hat getrunken",
    type: "Verb",
    meaning: "喝；饮用",
    example: "Ich trinke morgens eine Tasse Tee.",
    exampleZh: "我早上喝一杯茶。",
    grammarTitle: "饮用物使用第四格",
    grammar:
      "所喝的饮品作第四格宾语。trinken 是不规则动词，但现在时第三人称单数仍为 trinkt。",
    memory: "看到 Trinkwasser，就能拆出 trinken“喝”和 Wasser“水”。",
    storyDe: "Nach dem Aufstehen trinkt Mia zuerst eine Tasse Tee.",
    storyZh: "起床后，米娅先喝了一杯茶。",
  },
  {
    id: "a1-wasser",
    level: "A1",
    term: "das Wasser",
    forms: "das Wasser · meist ohne Plural",
    type: "Nomen",
    meaning: "水",
    example: "Kann ich bitte ein Glas Wasser haben?",
    exampleZh: "可以请给我一杯水吗？",
    grammarTitle: "通常不使用复数",
    grammar:
      "Wasser 是中性物质名词。表示一般意义的水时通常不加冠词，也不用复数：Ich trinke Wasser。",
    memory: "Wasser 和英语 water 很接近，都是“水”。",
    storyDe: "Für unterwegs füllt sie noch eine Flasche mit Wasser.",
    storyZh: "为了路上喝，她又装了一瓶水。",
  },
  {
    id: "a1-fahren",
    level: "A1",
    term: "fahren",
    forms: "fährt · fuhr · ist gefahren",
    type: "Verb",
    meaning: "乘车；驾驶；行驶",
    example: "Ich fahre jeden Tag mit dem Bus zur Arbeit.",
    exampleZh: "我每天乘公交车去上班。",
    grammarTitle: "交通工具使用 mit + 第三格",
    grammar:
      "表示乘坐某种交通工具时使用 mit 加第三格。表示从一处移动到另一处时，完成时通常使用 sein。",
    memory: "Fahrt 是一次行程，Fahrrad 是自行车，它们都包含 fahr-。",
    storyDe: "Um halb acht fährt Mia mit dem Bus ins Büro.",
    storyZh: "七点半，米娅乘公交车去办公室。",
  },
  {
    id: "a1-lernen",
    level: "A1",
    term: "lernen",
    forms: "lernt · lernte · hat gelernt",
    type: "Verb",
    meaning: "学习；学会",
    example: "Wir lernen heute zehn neue Wörter.",
    exampleZh: "我们今天学习十个新单词。",
    grammarTitle: "lernen 与 studieren",
    grammar:
      "lernen 可用于学习语言、单词或技能；studieren 通常表示在大学攻读某一专业。",
    memory: "学习者是 Lerner，正在做的动作就是 lernen。",
    storyDe: "Unterwegs lernt sie fünf neue deutsche Wörter.",
    storyZh: "路上，她学习了五个新的德语单词。",
  },
  {
    id: "a1-sprechen",
    level: "A1",
    term: "sprechen",
    forms: "spricht · sprach · hat gesprochen",
    type: "Verb",
    meaning: "说话；讲某种语言",
    example: "Meine Kollegin spricht sehr gut Deutsch.",
    exampleZh: "我的同事德语说得很好。",
    grammarTitle: "语言名称通常不加冠词",
    grammar:
      "表示讲某种语言时，语言名称通常直接放在动词后。与某人交谈使用 mit + 第三格。",
    memory: "德语 Spruch 和英语 speech 都能帮助联想到“说话”。",
    storyDe: "Im Büro spricht sie kurz mit ihrem Kollegen Ben.",
    storyZh: "在办公室，她和同事本简单聊了几句。",
  },
  {
    id: "a1-zusammen",
    level: "A1",
    term: "zusammen",
    forms: "zusammen",
    type: "Adverb",
    meaning: "一起；共同",
    example: "Wir kochen heute zusammen.",
    exampleZh: "我们今天一起做饭。",
    grammarTitle: "直接修饰动作",
    grammar:
      "zusammen 是副词，没有词尾变化，常放在句子中部，用来说明几个人共同完成一个动作。",
    memory: "看到大家聚在同一个地方，就想到 zusammen“一起”。",
    storyDe: "In der Mittagspause essen alle Kollegen zusammen.",
    storyZh: "午休时，所有同事一起吃饭。",
  },
  {
    id: "a1-heute",
    level: "A1",
    term: "heute",
    forms: "heute",
    type: "Adverb",
    meaning: "今天",
    example: "Heute habe ich keinen Deutschkurs.",
    exampleZh: "我今天没有德语课。",
    grammarTitle: "时间放在句首时动词仍居第二位",
    grammar:
      "heute 可以放在句首强调时间。它占据第一位后，变位动词紧跟其后，主语移到动词之后。",
    memory: "把 heute、gestern、morgen 作为“今天、昨天、明天”一组记忆。",
    storyDe: "Heute endet die Arbeit etwas früher als sonst.",
    storyZh: "今天的工作比平时结束得早一些。",
  },
  {
    id: "a1-schlafen",
    level: "A1",
    term: "schlafen",
    forms: "schläft · schlief · hat geschlafen",
    type: "Verb",
    meaning: "睡觉",
    example: "Das Kind schläft schon.",
    exampleZh: "孩子已经睡着了。",
    grammarTitle: "第二、三人称出现变音",
    grammar:
      "现在时中，du 和 er/sie/es 的 a 变为 ä：du schläfst、sie schläft。完成时使用 haben。",
    memory: "Schlafzimmer 是“卧室”，其中 Schlaf 就是“睡眠”。",
    storyDe: "Um zehn Uhr liegt Mia im Bett und schläft schon ruhig.",
    storyZh: "十点，米娅躺在床上，已经安静地睡着了。",
  },
] satisfies WordbookEntry[];

export const A2_WORDS = [
  {
    id: "a2-umziehen",
    level: "A2",
    term: "umziehen",
    forms: "trennbar · zieht um · zog um · ist umgezogen",
    type: "Verb",
    meaning: "搬家",
    example: "Wir ziehen nächsten Monat nach Leipzig um.",
    exampleZh: "我们下个月搬到莱比锡。",
    grammarTitle: "表示搬家时使用 sein",
    grammar:
      "表示搬家时，umziehen 是非反身的可分动词，完成时为 ist umgezogen。城市名前通常使用 nach。",
    memory: "ziehen 是“移动”，um- 表示换到另一处——整个家一起移动。",
    storyDe: "Am Montag zieht Lina für eine neue Stelle nach Hamburg um.",
    storyZh: "星期一，莉娜为了新工作搬到了汉堡。",
  },
  {
    id: "a2-wohnung",
    level: "A2",
    term: "die Wohnung",
    forms: "die Wohnung · die Wohnungen",
    type: "Nomen",
    meaning: "住宅；公寓",
    example: "Die Wohnung hat zwei Zimmer und einen Balkon.",
    exampleZh: "这套公寓有两个房间和一个阳台。",
    grammarTitle: "-ung 名词通常为阴性",
    grammar:
      "以 -ung 结尾的名词通常使用 die，复数一般加 -en：die Wohnungen。",
    memory: "wohnen 是“居住”，Wohnung 就是用来居住的地方。",
    storyDe: "Nach kurzer Suche findet sie eine helle Wohnung nahe der Firma.",
    storyZh: "找了不久，她就在公司附近找到了一套明亮的公寓。",
  },
  {
    id: "a2-anmelden",
    level: "A2",
    term: "sich anmelden",
    forms: "trennbar · meldet sich an · meldete sich an · hat sich angemeldet",
    type: "Verb",
    meaning: "登记；报名；注册",
    example: "Ich melde mich für den Deutschkurs an.",
    exampleZh: "我报名参加德语课。",
    grammarTitle: "反身代词与介词",
    grammar:
      "主语与登记的人相同时使用反身代词 mich、dich、sich。für 加第四格表示报名的项目，bei 加第三格表示登记的机构。",
    memory: "melden 是“报告”，an- 像走到柜台前报上自己的信息。",
    storyDe: "Noch am selben Tag meldet sie sich im Bürgerbüro an.",
    storyZh: "就在当天，她去市民服务处办理了登记。",
  },
  {
    id: "a2-erfahrung",
    level: "A2",
    term: "die Erfahrung",
    forms: "die Erfahrung · die Erfahrungen",
    type: "Nomen",
    meaning: "经验；经历",
    example: "Der Umzug war eine neue Erfahrung für mich.",
    exampleZh: "这次搬家对我来说是一段新的经历。",
    grammarTitle: "经验与一次经历",
    grammar:
      "不可数地谈“经验”时常用 Erfahrung haben；谈具体经历时可说 eine Erfahrung，复数为 Erfahrungen。",
    memory: "erfahren 可以表示“得知、亲身经历”，经历留下来的就是 Erfahrung。",
    storyDe: "Für sie ist alles neu, aber jede Erfahrung macht sie sicherer.",
    storyZh: "对她来说一切都很新，但每一次经历都让她更加从容。",
  },
  {
    id: "a2-teilnehmen",
    level: "A2",
    term: "teilnehmen",
    forms: "trennbar · nimmt teil · nahm teil · hat teilgenommen",
    type: "Verb",
    meaning: "参加；参与",
    example: "Nimmst du am Sprachkurs teil?",
    exampleZh: "你参加这个语言课程吗？",
    grammarTitle: "teilnehmen an + 第三格",
    grammar:
      "参加的活动放在 an 后并使用第三格。an dem 常缩写为 am：am Kurs teilnehmen。",
    memory: "Teil 是“一部分”，nehmen 是“拿取”——成为活动的一部分，就是参加。",
    storyDe: "In der Firma nimmt sie an einem Einführungskurs teil.",
    storyZh: "在公司里，她参加了一门入职培训课。",
  },
  {
    id: "a2-vorschlagen",
    level: "A2",
    term: "vorschlagen",
    forms: "trennbar · schlägt vor · schlug vor · hat vorgeschlagen",
    type: "Verb",
    meaning: "建议；提议",
    example: "Ich schlage vor, heute früher anzufangen.",
    exampleZh: "我建议今天早点开始。",
    grammarTitle: "提出建议的两种结构",
    grammar:
      "可以使用 jemandem etwas vorschlagen；若建议一个动作，也可使用 vorschlagen, ... zu + Infinitiv。",
    memory: "把一个想法“放到大家面前”——vor + schlagen，就是提出建议。",
    storyDe: "Eine Kollegin schlägt vor, mittags zusammen zu essen.",
    storyZh: "一位同事提议中午一起吃饭。",
  },
  {
    id: "a2-sich-freuen",
    level: "A2",
    term: "sich freuen auf/über",
    forms: "freut sich · freute sich · hat sich gefreut",
    type: "Verb",
    meaning: "期待；为……感到高兴",
    example: "Ich freue mich auf meinen ersten Arbeitstag.",
    exampleZh: "我很期待第一天上班。",
    grammarTitle: "auf 与 über 的区别",
    grammar:
      "sich freuen auf + 第四格表示期待尚未发生的事；sich freuen über + 第四格表示为已经存在或发生的事高兴。",
    memory: "auf 向前看，所以是期待未来；über 是对眼前或已经发生的事感到高兴。",
    storyDe: "Lina freut sich auf das gemeinsame Essen und neue Gespräche.",
    storyZh: "莉娜很期待这顿聚餐和新的交谈。",
  },
  {
    id: "a2-puenktlich",
    level: "A2",
    term: "pünktlich",
    forms: "pünktlich · pünktlicher · am pünktlichsten",
    type: "Adjektiv",
    meaning: "准时的；准时地",
    example: "Bitte sei morgen pünktlich.",
    exampleZh: "请你明天准时到。",
    grammarTitle: "也可直接修饰动作",
    grammar:
      "pünktlich 作表语或副词时不加词尾：Der Zug ist pünktlich；作定语放在名词前时需要词尾变化。",
    memory: "Punkt 是“点”，在约定的时间点到达就是 pünktlich。",
    storyDe: "Am nächsten Morgen ist sie pünktlich im Büro.",
    storyZh: "第二天早上，她准时到了办公室。",
  },
  {
    id: "a2-trotzdem",
    level: "A2",
    term: "trotzdem",
    forms: "trotzdem",
    type: "Adverb",
    meaning: "尽管如此；仍然",
    example: "Es regnet. Trotzdem fahren wir mit dem Fahrrad.",
    exampleZh: "下雨了。尽管如此，我们还是骑自行车去。",
    grammarTitle: "句首 trotzdem 后动词仍居第二位",
    grammar:
      "trotzdem 是连接副词。放在句首时占据第一位，因此变位动词紧跟其后，主语放到动词之后。",
    memory: "前面有阻碍，后面的事情“仍然”发生。",
    storyDe:
      "Draußen regnet es stark; trotzdem erkundet sie am Abend ihr Viertel.",
    storyZh: "外面雨下得很大；尽管如此，她晚上还是探索了自己的新街区。",
  },
  {
    id: "a2-sich-gewoehnen",
    level: "A2",
    term: "sich gewöhnen an",
    forms: "gewöhnt sich · gewöhnte sich · hat sich gewöhnt",
    type: "Verb",
    meaning: "习惯于",
    example: "Ich gewöhne mich langsam an den neuen Arbeitsweg.",
    exampleZh: "我正在慢慢习惯新的上班路线。",
    grammarTitle: "sich gewöhnen an + 第四格",
    grammar:
      "这是反身结构，反身代词随主语变化；所适应的人或事放在 an 后并使用第四格。",
    memory: "Gewohnheit 是“习惯”；sich gewöhnen 是让自己逐渐形成这个习惯。",
    storyDe: "Nach einigen Wochen hat sich Lina an ihr neues Leben gewöhnt.",
    storyZh: "几周后，莉娜已经习惯了新的生活。",
  },
  {
    id: "a2-umgebung",
    level: "A2",
    term: "die Umgebung",
    forms: "die Umgebung · die Umgebungen",
    type: "Nomen",
    meaning: "周边地区；环境",
    example: "Gibt es in der Umgebung einen Supermarkt?",
    exampleZh: "这附近有超市吗？",
    grammarTitle: "in der Umgebung",
    grammar:
      "表示“在附近”时常使用 in der Umgebung；表示某地的周边，也可以说 die Umgebung von + 第三格。",
    memory: "想象把一个地方围上一圈，圈内周边的一切就是 Umgebung。",
    storyDe:
      "Inzwischen kennt Lina die Umgebung ihrer neuen Wohnung schon besser.",
    storyZh: "现在，莉娜已经更熟悉新公寓周围的环境了。",
  },
  {
    id: "a2-kennenlernen",
    level: "A2",
    term: "kennenlernen",
    forms: "trennbar · lernt kennen · lernte kennen · hat kennengelernt",
    type: "Verb",
    meaning: "结识；初次了解",
    example: "Auf der Feier habe ich viele nette Leute kennengelernt.",
    exampleZh: "我在聚会上认识了许多友善的人。",
    grammarTitle: "kennen 与 kennenlernen",
    grammar:
      "kennen 表示已经认识；kennenlernen 强调第一次认识或逐步了解。认识的人或事使用第四格。",
    memory: "kennen“认识”加 lernen“学习”，就是开始认识并了解。",
    storyDe: "Am Samstag lernt sie ihren Nachbarn Amir kennen.",
    storyZh: "星期六，她认识了邻居阿米尔。",
  },
  {
    id: "a2-einladen",
    level: "A2",
    term: "einladen",
    forms: "trennbar · lädt ein · lud ein · hat eingeladen",
    type: "Verb",
    meaning: "邀请；请客",
    example: "Wir laden unsere Freunde zum Abendessen ein.",
    exampleZh: "我们邀请朋友们来吃晚饭。",
    grammarTitle: "jemanden zu etwas einladen",
    grammar:
      "受邀请的人使用第四格；活动通常放在 zu 后并使用第三格：jemanden zu einer Feier einladen。",
    memory: "把客人请“进来”参加活动，就是 einladen。",
    storyDe: "Amir lädt sie zu einem kleinen Straßenfest ein.",
    storyZh: "阿米尔邀请她参加一个小型街区节日。",
  },
  {
    id: "a2-mitbringen",
    level: "A2",
    term: "mitbringen",
    forms: "trennbar · bringt mit · brachte mit · hat mitgebracht",
    type: "Verb",
    meaning: "随身带来；捎来",
    example: "Kannst du bitte etwas zu trinken mitbringen?",
    exampleZh: "你可以带些喝的来吗？",
    grammarTitle: "jemandem etwas mitbringen",
    grammar:
      "带来的东西使用第四格；若说明为谁带来，该人使用第三格。陈述句中 mit 放到句末。",
    memory: "mit 是“一起、随同”，bringen 是“带来”——随手一起带来。",
    storyDe: "Lina bringt selbst gemachten Kartoffelsalat mit.",
    storyZh: "莉娜带来了自己做的土豆沙拉。",
  },
  {
    id: "a2-obwohl",
    level: "A2",
    term: "obwohl",
    forms: "obwohl",
    type: "Konjunktion",
    meaning: "尽管；虽然",
    example: "Obwohl es regnet, gehen wir spazieren.",
    exampleZh: "虽然下雨，我们还是去散步。",
    grammarTitle: "从句动词放在句末",
    grammar:
      "obwohl 引导让步从句，变位动词放在从句末尾。obwohl 从句在前时，后面的主句直接以变位动词开始。",
    memory: "obwohl 常与 trotzdem 成对理解：虽然有阻碍，事情仍然发生。",
    storyDe:
      "Obwohl Lina dort nur wenige Menschen kennt, fühlt sie sich willkommen.",
    storyZh: "虽然莉娜在那里只认识几个人，但她感到很受欢迎。",
  },
  {
    id: "a2-interessieren",
    level: "A2",
    term: "sich interessieren für",
    forms: "interessiert sich · interessierte sich · hat sich interessiert",
    type: "Verb",
    meaning: "对……感兴趣",
    example: "Ich interessiere mich für deutsche Geschichte.",
    exampleZh: "我对德国历史感兴趣。",
    grammarTitle: "für + 第四格",
    grammar:
      "感兴趣的人使用反身代词 mich、dich、sich；感兴趣的对象放在 für 后并使用第四格。",
    memory: "interessieren 与英语 interest 相近，再记住后面固定跟 für。",
    storyDe:
      "Auf dem Fest interessiert sie sich besonders für den Sportverein im Viertel.",
    storyZh: "在节日活动上，她对街区里的体育俱乐部尤其感兴趣。",
  },
  {
    id: "a2-deshalb",
    level: "A2",
    term: "deshalb",
    forms: "deshalb",
    type: "Adverb",
    meaning: "因此；所以",
    example: "Der Bus kommt nicht. Deshalb gehe ich zu Fuß.",
    exampleZh: "公交车不来了，所以我步行去。",
    grammarTitle: "deshalb 后动词居第二位",
    grammar:
      "deshalb 是连接副词，用来引出前一句原因造成的结果。放在句首时，变位动词紧跟其后。",
    memory: "前一句给出原因，deshalb 后面马上说明结果。",
    storyDe: "Deshalb spricht sie noch am selben Abend mit dem Trainer.",
    storyZh: "因此，她当晚就和教练聊了聊。",
  },
  {
    id: "a2-verbessern",
    level: "A2",
    term: "verbessern",
    forms: "verbessert · verbesserte · hat verbessert",
    type: "Verb",
    meaning: "改善；提高",
    example: "Ich möchte meine Aussprache verbessern.",
    exampleZh: "我想提高自己的发音。",
    grammarTitle: "verbessern 与 sich verbessern",
    grammar:
      "主动提高某事物时使用 etwas verbessern；某事物自身变好时使用 sich verbessern。ver- 不可分，完成时不加 ge-。",
    memory: "besser 是“更好”，verbessern 就是使某事变得更好。",
    storyDe: "Durch die neuen Gespräche verbessert Lina außerdem ihr Deutsch.",
    storyZh: "通过这些新的交谈，莉娜的德语也得到了提高。",
  },
  {
    id: "a2-alltag",
    level: "A2",
    term: "der Alltag",
    forms: "der Alltag · meist Singular",
    type: "Nomen",
    meaning: "日常生活",
    example: "Im Alltag fahre ich meistens mit dem Fahrrad.",
    exampleZh: "日常生活中，我通常骑自行车出行。",
    grammarTitle: "固定表达 im Alltag",
    grammar:
      "Alltag 通常使用单数。表示“在日常生活中”时常说 im Alltag，其中 im 是 in dem 的缩写。",
    memory: "all + Tag 可以理解为“每一天”，合起来就是日常生活。",
    storyDe: "Langsam fühlt sich ihr neuer Alltag nicht mehr fremd an.",
    storyZh: "慢慢地，她的新生活不再让她感到陌生。",
  },
  {
    id: "a2-termin",
    level: "A2",
    term: "der Termin",
    forms: "der Termin · die Termine",
    type: "Nomen",
    meaning: "预约；约定时间",
    example: "Ich habe morgen einen Termin beim Zahnarzt.",
    exampleZh: "我明天预约了牙医。",
    grammarTitle: "einen Termin haben",
    grammar:
      "表示已有预约常说 einen Termin haben；表示约时间可说 einen Termin vereinbaren。与某人或某机构的预约常使用 bei + 第三格。",
    memory: "把 Termin 想成日程表上已经确定的一个时间点。",
    storyDe:
      "Am Montag hat Lina ihren ersten Termin bei einer neuen Hausärztin.",
    storyZh: "星期一，莉娜第一次预约了新的家庭医生。",
  },
] satisfies WordbookEntry[];
