export type AdvancedWordEntry = {
  id: string;
  level: "B1" | "B2" | "C1";
  term: string;
  forms: string;
  type: string;
  meaning: string;
  example: string;
  exampleZh: string;
  grammarTitle: string;
  grammar: string;
  memory: string;
  storyDe: string;
  storyZh: string;
};

export const B1_ADDITIONS = [
  {
    id: "b1-bemerken",
    level: "B1",
    term: "bemerken",
    forms: "bemerken · bemerkt · bemerkte · hat bemerkt",
    type: "Verb",
    meaning: "注意到；察觉",
    example: "Er bemerkte erst später, dass seine Tasche fehlte.",
    exampleZh: "他过了一会儿才注意到自己的包不见了。",
    grammarTitle: "etw. bemerken / bemerken, dass ...",
    grammar: "可直接接第四格宾语，也可接 dass 从句。be- 是不可分前缀，完成分词不加 ge-。",
    memory: "某件事进入你的注意范围，被你察觉到了。",
    storyDe: "Am nächsten Morgen bemerkte Mara, dass die Baustelle noch nicht beendet war.",
    storyZh: "第二天早晨，玛拉注意到施工还没有结束。",
  },
  {
    id: "b1-richtung",
    level: "B1",
    term: "die Richtung",
    forms: "die Richtung · die Richtungen",
    type: "Nomen · feminin",
    meaning: "方向；方位",
    example: "Wir liefen in die falsche Richtung.",
    exampleZh: "我们走错了方向。",
    grammarTitle: "in eine Richtung",
    grammar: "表示朝某方向移动时，in 后使用第四格；表示位于某个方向时使用第三格。",
    memory: "richten 有“对准”的意思，对准哪里便决定了方向。",
    storyDe: "Auf einem Schild stand, in welche Richtung Fußgänger gehen sollten.",
    storyZh: "一块指示牌上写着行人应当朝哪个方向走。",
  },
  {
    id: "b1-beeilen",
    level: "B1",
    term: "sich beeilen",
    forms: "beeilt sich · beeilte sich · hat sich beeilt",
    type: "Reflexives Verb",
    meaning: "赶快；加快速度",
    example: "Wir müssen uns beeilen, sonst verpassen wir den Zug.",
    exampleZh: "我们必须快一点，否则就要错过火车了。",
    grammarTitle: "sich beeilen, um ... zu ...",
    grammar: "反身代词随主语变化：ich beeile mich、du beeilst dich。可用 um ... zu 说明赶时间的目的。",
    memory: "时间紧张时，让自己动作快起来。",
    storyDe: "Da sie einen frühen Termin hatte, musste sie sich beeilen.",
    storyZh: "因为她有一个很早的约会，所以必须加快脚步。",
  },
  {
    id: "b1-entgegenkommen",
    level: "B1",
    term: "entgegenkommen",
    forms: "kommt entgegen · kam entgegen · ist entgegengekommen",
    type: "Verb · trennbar",
    meaning: "迎面走来；迁就或通融",
    example: "Auf dem schmalen Weg kam uns eine Gruppe Wanderer entgegen.",
    exampleZh: "在狭窄的小路上，一群徒步者迎面向我们走来。",
    grammarTitle: "jdm. entgegenkommen + Dativ",
    grammar: "对象使用第三格。表示实际移动时完成时使用 sein；引申义可表示在要求或价格上向某人让步。",
    memory: "entgegen 是“朝着对面”，kommen 是“来”，组合起来就是迎面而来。",
    storyDe: "Unterwegs kam ihr ein älterer Nachbar entgegen, der den richtigen Weg suchte.",
    storyZh: "途中，一位正在寻找正确路线的年长邻居迎面走来。",
  },
  {
    id: "b1-haltestelle",
    level: "B1",
    term: "die Haltestelle",
    forms: "die Haltestelle · die Haltestellen",
    type: "Nomen · feminin",
    meaning: "公交车或电车站",
    example: "Der Bus hält an der nächsten Haltestelle.",
    exampleZh: "公交车会在下一站停靠。",
    grammarTitle: "an der Haltestelle / bis zur Haltestelle",
    grammar: "表示静止位置用 an + Dativ；表示走到车站为止常用 bis zu + Dativ。",
    memory: "halten 是“停下”，Stelle 是“地点”：车辆停下的地点。",
    storyDe: "Mara begleitete ihn bis zur nächsten Haltestelle und zeigte ihm dort den Fahrplan.",
    storyZh: "玛拉陪他走到下一处车站，并在那里给他看了时刻表。",
  },
  {
    id: "b1-bescheid-geben",
    level: "B1",
    term: "Bescheid geben",
    forms: "gibt Bescheid · gab Bescheid · hat Bescheid gegeben",
    type: "Feste Wendung",
    meaning: "通知；告知一声",
    example: "Bitte gib mir Bescheid, wenn du zu Hause angekommen bist.",
    exampleZh: "你到家后请告诉我一声。",
    grammarTitle: "jdm. Bescheid geben",
    grammar: "被通知的人用第三格；内容可用 über + Akkusativ、wenn 或 dass 从句表达。Bescheid 必须大写。",
    memory: "不是正式长篇说明，而是及时把情况告诉对方一声。",
    storyDe: "Anschließend gab sie ihrer Kollegin Bescheid, dass sie etwas später kommen würde.",
    storyZh: "随后，她通知同事自己会晚一点到。",
  },
  {
    id: "b1-erleichtert",
    level: "B1",
    term: "erleichtert",
    forms: "erleichtert · erleichterter · am erleichtertsten",
    type: "Adjektiv",
    meaning: "如释重负的；感到宽慰的",
    example: "Sie war erleichtert, als sie die gute Nachricht hörte.",
    exampleZh: "听到这个好消息时，她如释重负。",
    grammarTitle: "erleichtert sein, dass / als ...",
    grammar: "常作表语描述人的感受；原因可用 über + Akkusativ、dass 从句或 als 从句说明。",
    memory: "leicht 是“轻”；担心消失后，心里重新变轻。",
    storyDe: "Trotz der Verzögerung war Mara erleichtert, als ihr Nachbar sicher in den richtigen Bus stieg.",
    storyZh: "尽管耽误了时间，看到邻居安全坐上正确的公交车，玛拉还是感到很宽慰。",
  },
  {
    id: "b1-lohnen",
    level: "B1",
    term: "sich lohnen",
    forms: "lohnt sich · lohnte sich · hat sich gelohnt",
    type: "Reflexives Verb",
    meaning: "值得；有回报",
    example: "Es lohnt sich, diese Ausstellung früh zu besuchen.",
    exampleZh: "早点参观这个展览是值得的。",
    grammarTitle: "es lohnt sich, ... zu ...",
    grammar: "可由事物作主语：Der Aufwand lohnt sich；也常使用无人称结构 es lohnt sich, zu + Infinitiv。",
    memory: "付出的时间或力气最终得到有价值的结果。",
    storyDe: "Der kleine Umweg hatte sich gelohnt, weil Mara damit jemandem helfen konnte.",
    storyZh: "这个小小的绕路很值得，因为玛拉因此帮助了别人。",
  },
] satisfies readonly AdvancedWordEntry[];

export const C1_WORDS = [
  {
    id: "c1-herangehensweise",
    level: "C1",
    term: "die Herangehensweise",
    forms: "die Herangehensweise · die Herangehensweisen",
    type: "Nomen · feminin",
    meaning: "处理方式；研究方法；着手路径",
    example: "Eine interdisziplinäre Herangehensweise an das Problem eröffnet neue Perspektiven.",
    exampleZh: "以跨学科方式处理这个问题，可以带来新的视角。",
    grammarTitle: "Herangehensweise an + Akkusativ",
    grammar: "使用 an + Akkusativ 说明所处理的对象。与 Methode 相比，它更强调着手解决问题的整体路径。",
    memory: "herangehen 是走近并着手处理，Herangehensweise 就是如何走近问题。",
    storyDe: "Ein Forschungsteam untersuchte, wie künstliche Intelligenz Schulen verändern könnte, und wählte dafür eine interdisziplinäre Herangehensweise.",
    storyZh: "一个研究团队考察人工智能可能如何改变学校，并为此选择了跨学科的研究路径。",
  },
  {
    id: "c1-differenziert",
    level: "C1",
    term: "differenziert",
    forms: "differenziert · differenzierter · am differenziertesten",
    type: "Adjektiv / Adverb",
    meaning: "有区分地；细致而有层次的",
    example: "Die Ergebnisse müssen differenziert betrachtet werden.",
    exampleZh: "必须对这些结果进行细致且有区分的分析。",
    grammarTitle: "etw. differenziert betrachten",
    grammar: "常与 betrachten、darstellen、beurteilen 搭配。作副词时不变；作定语时按普通形容词添加词尾。",
    memory: "不是简单分成好或坏，而是辨认其中不同的层次与条件。",
    storyDe: "Statt pauschaler Urteile betrachteten die Forschenden die Chancen und Risiken differenziert.",
    storyZh: "研究人员没有作笼统判断，而是有层次地分析机会与风险。",
  },
  {
    id: "c1-veranschaulichen",
    level: "C1",
    term: "veranschaulichen",
    forms: "veranschaulichen · veranschaulicht · veranschaulichte · hat veranschaulicht",
    type: "Verb",
    meaning: "形象说明；使清楚易懂",
    example: "Die Grafik veranschaulicht, wie sich der Energieverbrauch entwickelt hat.",
    exampleZh: "这张图直观展示了能源消耗的变化过程。",
    grammarTitle: "jdm. etw. veranschaulichen",
    grammar: "可同时带第三格的人和第四格的内容。ver- 是不可分前缀，完成分词不加 ge-。",
    memory: "Anschauung 与观看和直观认识有关；让内容仿佛能被看见。",
    storyDe: "Konkrete Unterrichtsszenarien veranschaulichten, wie die Technik Lehrkräfte entlasten könnte.",
    storyZh: "具体的课堂情境直观说明了这项技术可能如何减轻教师负担。",
  },
  {
    id: "c1-abwaegung",
    level: "C1",
    term: "die Abwägung",
    forms: "die Abwägung · die Abwägungen",
    type: "Nomen · feminin",
    meaning: "权衡；综合考量",
    example: "Nach sorgfältiger Abwägung aller Argumente stimmte der Ausschuss dem Vorschlag zu.",
    exampleZh: "在仔细权衡所有论点后，委员会同意了该提案。",
    grammarTitle: "Abwägung zwischen + Dativ",
    grammar: "常用 Abwägung zwischen A und B；也常见 nach sorgfältiger Abwägung aller Umstände。对应动词是 abwägen。",
    memory: "Waage 是天平；把不同因素放在天平两端，就是 Abwägung。",
    storyDe: "Jede Empfehlung beruhte auf einer sorgfältigen Abwägung zwischen pädagogischem Nutzen und möglichen Nebenwirkungen.",
    storyZh: "每项建议都建立在对教学价值和潜在副作用的谨慎权衡之上。",
  },
  {
    id: "c1-unerlaesslich",
    level: "C1",
    term: "unerlässlich",
    forms: "unerlässlich · meist nicht gesteigert",
    type: "Adjektiv",
    meaning: "不可或缺的；必不可少的",
    example: "Transparente Regeln sind für den verantwortungsvollen Einsatz unerlässlich.",
    exampleZh: "透明的规则对于负责任地使用该技术必不可少。",
    grammarTitle: "unerlässlich für + Akkusativ",
    grammar: "常作表语，并与 für + Akkusativ 搭配；也可使用 unerlässlich, um ... zu ... 表示必要条件。",
    memory: "不能被省去或丢下的，就是 unerlässlich。",
    storyDe: "Dabei galten Datenschutz und nachvollziehbare Entscheidungen als unerlässlich.",
    storyZh: "在这一过程中，数据保护和可解释的决策被视为不可或缺。",
  },
  {
    id: "c1-erschliessen",
    level: "C1",
    term: "sich erschließen",
    forms: "erschließt sich · erschloss sich · hat sich erschlossen",
    type: "Reflexives Verb",
    meaning: "逐渐显现；为某人所理解",
    example: "Die Bedeutung dieser Passage erschließt sich vielen erst beim zweiten Lesen.",
    exampleZh: "许多人读到第二遍时才理解这段文字的含义。",
    grammarTitle: "etw. erschließt sich jdm.",
    grammar: "事物作第一格主语，理解者用第三格：Der Sinn erschließt sich mir。不能把理解者直接作为主语。",
    memory: "像一扇原本关闭的门慢慢打开，意义才逐渐显现出来。",
    storyDe: "Die Bedeutung dieser Voraussetzungen erschloss sich vielen Beteiligten erst im Verlauf der Gespräche.",
    storyZh: "许多参与者直到讨论逐步展开后，才理解这些前提的重要性。",
  },
  {
    id: "c1-weitreichend",
    level: "C1",
    term: "weitreichend",
    forms: "weitreichend · weitreichender · am weitreichendsten",
    type: "Adjektiv",
    meaning: "影响深远的；涉及范围广的",
    example: "Die Entscheidung könnte weitreichende Folgen für den Arbeitsmarkt haben.",
    exampleZh: "这一决定可能会对劳动力市场产生深远影响。",
    grammarTitle: "weitreichende Folgen",
    grammar: "常与 Folgen、Veränderungen、Reformen 或 Befugnisse 搭配。作定语时按普通形容词规则添加词尾。",
    memory: "影响能够伸展到很远的地方，因此不是局部或短期的。",
    storyDe: "Allen wurde bewusst, dass vorschnelle Entscheidungen weitreichende Folgen haben könnten.",
    storyZh: "所有人都意识到，仓促的决定可能带来深远后果。",
  },
  {
    id: "c1-tragweite",
    level: "C1",
    term: "die Tragweite",
    forms: "die Tragweite · meist nur im Singular",
    type: "Nomen · feminin",
    meaning: "影响范围；重大意义；深远程度",
    example: "Die Tragweite der Reform wurde anfangs unterschätzt.",
    exampleZh: "这项改革的深远影响起初被低估了。",
    grammarTitle: "die Tragweite + Genitiv",
    grammar: "常用第二格说明事项：die Tragweite der Entscheidung。固定表达是 etw. in seiner vollen Tragweite erkennen。",
    memory: "一件事的影响能承载并延伸多远，就是它的 Tragweite。",
    storyDe: "Der Abschlussbericht machte deshalb deutlich, dass die gesellschaftliche Tragweite der Technologie kontinuierlich überprüft werden muss.",
    storyZh: "因此，最终报告明确指出，必须持续审视这项技术所具有的社会影响。",
  },
  {
    id: "c1-erkenntnis",
    level: "C1",
    term: "die Erkenntnis",
    forms: "die Erkenntnis · die Erkenntnisse",
    type: "Nomen · feminin",
    meaning: "认识；研究所得的结论或洞见",
    example: "Die Untersuchung führte zu neuen Erkenntnissen über das Lernverhalten.",
    exampleZh: "这项调查带来了有关学习行为的新认识。",
    grammarTitle: "zu der Erkenntnis gelangen, dass ...",
    grammar: "常与 gewinnen、führen zu 或 gelangen zu 搭配。接内容从句时常用 die Erkenntnis, dass ...。",
    memory: "不是一般的 Kenntnis，而是经过观察和思考后获得的深层认识。",
    storyDe: "Eine zentrale Erkenntnis war, dass technische Qualität allein keinen pädagogischen Erfolg garantiert.",
    storyZh: "一项核心认识是，单凭技术质量并不能保证教学成功。",
  },
  {
    id: "c1-massgeblich",
    level: "C1",
    term: "maßgeblich",
    forms: "maßgeblich · maßgeblicher · am maßgeblichsten",
    type: "Adjektiv / Adverb",
    meaning: "起决定作用的；显著地",
    example: "Ihre Forschung hat die öffentliche Debatte maßgeblich geprägt.",
    exampleZh: "她的研究显著影响了公共讨论。",
    grammarTitle: "maßgeblich für / maßgeblich beitragen",
    grammar: "常用 maßgeblich für + Akkusativ sein 或 maßgeblich zu + Dativ beitragen，表示对结果具有关键影响。",
    memory: "Maßstab 是衡量标准；能够决定衡量尺度的因素便是 maßgeblich。",
    storyDe: "Maßgeblich war vielmehr, wie gut die Lehrkräfte auf den Einsatz vorbereitet wurden.",
    storyZh: "真正起决定作用的，是教师为使用这项技术所做的准备是否充分。",
  },
  {
    id: "c1-rahmenbedingung",
    level: "C1",
    term: "die Rahmenbedingung",
    forms: "die Rahmenbedingung · die Rahmenbedingungen",
    type: "Nomen · feminin",
    meaning: "框架条件；外部基础条件",
    example: "Politische Entscheidungen verändern die wirtschaftlichen Rahmenbedingungen.",
    exampleZh: "政治决策会改变经济运行的框架条件。",
    grammarTitle: "通常使用复数",
    grammar: "多以复数 Rahmenbedingungen 出现，指行动无法忽视的法律、经济、组织或社会环境。",
    memory: "它像画框一样，规定一项计划可以在哪些边界内展开。",
    storyDe: "Zudem unterschieden sich die technischen und sozialen Rahmenbedingungen von Schule zu Schule erheblich.",
    storyZh: "此外，各所学校的技术与社会条件存在显著差异。",
  },
  {
    id: "c1-nachvollziehbarkeit",
    level: "C1",
    term: "die Nachvollziehbarkeit",
    forms: "die Nachvollziehbarkeit · meist im Singular",
    type: "Nomen · feminin",
    meaning: "可理解性；可追溯性；透明程度",
    example: "Die Nachvollziehbarkeit behördlicher Entscheidungen stärkt das Vertrauen.",
    exampleZh: "政府决策的可理解性有助于增强信任。",
    grammarTitle: "Nachvollziehbarkeit einer Sache",
    grammar: "常通过第二格或 von + Dativ 说明对象。可指论证是否易懂，也可指过程是否能够追溯。",
    memory: "别人能否沿着同一条思路重新走一遍并理解结果。",
    storyDe: "Für die Akzeptanz spielte die Nachvollziehbarkeit automatisierter Empfehlungen eine zentrale Rolle.",
    storyZh: "自动生成的建议是否易于理解，对人们接受该系统起着关键作用。",
  },
  {
    id: "c1-stellenwert",
    level: "C1",
    term: "der Stellenwert",
    forms: "der Stellenwert · meist im Singular",
    type: "Nomen · maskulin",
    meaning: "重要性；地位；价值权重",
    example: "Gesundheit hat für viele Menschen einen hohen Stellenwert.",
    exampleZh: "健康对许多人而言具有很高的重要性。",
    grammarTitle: "einen hohen Stellenwert haben",
    grammar: "也可用 einer Sache einen hohen Stellenwert beimessen，其中被重视的事物使用第三格。",
    memory: "某件事在价值排序中占据什么位置，就是它的 Stellenwert。",
    storyDe: "Dem professionellen Urteil der Lehrkräfte wurde deshalb weiterhin ein hoher Stellenwert beigemessen.",
    storyZh: "因此，教师的专业判断依然受到高度重视。",
  },
  {
    id: "c1-vorbeugen",
    level: "C1",
    term: "vorbeugen",
    forms: "beugt vor · beugte vor · hat vorgebeugt",
    type: "Verb · trennbar",
    meaning: "预防；提前防止",
    example: "Regelmäßige Bewegung kann vielen gesundheitlichen Problemen vorbeugen.",
    exampleZh: "规律运动可以预防许多健康问题。",
    grammarTitle: "einer Sache vorbeugen + Dativ",
    grammar: "vorbeugen 支配第三格，而不是第四格：einem Missverständnis vorbeugen。前缀 vor- 可分。",
    memory: "在问题出现之前先向前弯身挡住它，即提前预防。",
    storyDe: "Klare Zuständigkeiten sollten Fehlanwendungen und einer blinden Abhängigkeit vom System vorbeugen.",
    storyZh: "明确的责任分工应当防止误用，也避免人们盲目依赖系统。",
  },
  {
    id: "c1-verzerrung",
    level: "C1",
    term: "die Verzerrung",
    forms: "die Verzerrung · die Verzerrungen",
    type: "Nomen · feminin",
    meaning: "扭曲；偏差；失真",
    example: "Eine einseitige Datenauswahl kann zu erheblichen Verzerrungen führen.",
    exampleZh: "片面选择数据可能造成严重偏差。",
    grammarTitle: "zu Verzerrungen führen",
    grammar: "常与 führen zu + Dativ、verursachen 或 vermeiden 搭配。在数据语境中可指系统性偏差。",
    memory: "原本的形状被拉歪，事实或数据也因此不再准确呈现现实。",
    storyDe: "Besondere Aufmerksamkeit galt möglichen Verzerrungen in den zugrunde liegenden Daten.",
    storyZh: "研究尤其关注底层数据中可能存在的偏差。",
  },
  {
    id: "c1-erweisen",
    level: "C1",
    term: "sich erweisen",
    forms: "erweist sich · erwies sich · hat sich erwiesen",
    type: "Reflexives Verb",
    meaning: "事实证明是；结果显示为",
    example: "Die vermeintlich einfache Aufgabe erwies sich als äußerst anspruchsvoll.",
    exampleZh: "这项看似简单的任务事实证明极具挑战性。",
    grammarTitle: "sich als ... erweisen",
    grammar: "常用 etw. erweist sich als + 名词或形容词，表示经过检验后显露出真实性质。",
    memory: "起初只是推测，后来由事实把真正结果展示出来。",
    storyDe: "In der Pilotphase erwies sich das System dort als hilfreich, wo es kontrolliert und gezielt eingesetzt wurde.",
    storyZh: "试点阶段表明，在受到监督并有针对性使用时，该系统确实能够提供帮助。",
  },
  {
    id: "c1-wechselwirkung",
    level: "C1",
    term: "die Wechselwirkung",
    forms: "die Wechselwirkung · die Wechselwirkungen",
    type: "Nomen · feminin",
    meaning: "相互作用；交互影响",
    example: "Die Studie untersucht die Wechselwirkung zwischen Sprache und sozialer Identität.",
    exampleZh: "这项研究考察语言与社会身份之间的相互作用。",
    grammarTitle: "Wechselwirkung zwischen + Dativ",
    grammar: "zwischen A und B 后均使用第三格。它强调双方彼此影响，而非单向因果关系。",
    memory: "wechseln 是相互交换；作用从两边来回发生。",
    storyDe: "Im Mittelpunkt stand die Wechselwirkung zwischen technischer Unterstützung und pädagogischer Verantwortung.",
    storyZh: "研究重点是技术支持与教学责任之间的相互作用。",
  },
  {
    id: "c1-verantwortbar",
    level: "C1",
    term: "verantwortbar",
    forms: "verantwortbar · meist nicht gesteigert",
    type: "Adjektiv",
    meaning: "可以负责任地接受或辩护的",
    example: "Ein solcher Eingriff ist nur unter strengen Bedingungen verantwortbar.",
    exampleZh: "只有在严格条件下，这样的干预才是可以负责地接受的。",
    grammarTitle: "verantwortbar sein",
    grammar: "常作表语，并与 unter + Dativ 或 nur wenn 搭配。它强调某项行为在伦理或专业上能够被承担。",
    memory: "能够对后果作出交代、承担责任，才称得上 verantwortbar。",
    storyDe: "Nur unter klar definierten Bedingungen erschien ein breiterer Einsatz gesellschaftlich verantwortbar.",
    storyZh: "只有在条件得到明确界定时，更大范围的应用在社会层面才是负责任的。",
  },
  {
    id: "c1-schlussfolgerung",
    level: "C1",
    term: "die Schlussfolgerung",
    forms: "die Schlussfolgerung · die Schlussfolgerungen",
    type: "Nomen · feminin",
    meaning: "结论；推论",
    example: "Aus den Daten lässt sich keine eindeutige Schlussfolgerung ziehen.",
    exampleZh: "无法从这些数据中得出明确结论。",
    grammarTitle: "eine Schlussfolgerung aus + Dativ ziehen",
    grammar: "常用 aus etw. eine Schlussfolgerung ziehen；也可通过 dass 从句说明结论的具体内容。",
    memory: "从已有事实一步步推到 Schluss，也就是最终结论。",
    storyDe: "Die Schlussfolgerung des Teams fiel daher bewusst zurückhaltend aus: Innovation brauche verbindliche Grenzen.",
    storyZh: "因此，团队有意作出了审慎的结论：创新需要具有约束力的边界。",
  },
  {
    id: "c1-rechnung-tragen",
    level: "C1",
    term: "einer Sache Rechnung tragen",
    forms: "trägt Rechnung · trug Rechnung · hat Rechnung getragen",
    type: "Feste Wendung",
    meaning: "充分考虑；顾及；对……作出相应安排",
    example: "Die neue Regelung trägt den Bedürfnissen kleiner Betriebe Rechnung.",
    exampleZh: "新规定充分考虑了小型企业的需求。",
    grammarTitle: "jdm. / etw. Rechnung tragen + Dativ",
    grammar: "固定搭配中的对象使用第三格，Rechnung 不加冠词且通常保持单数，不能按字面理解为携带账单。",
    memory: "像把一项因素正式记入账目一样，给予它应有的考虑。",
    storyDe: "Künftige Regelungen müssten sowohl den unterschiedlichen Schulen als auch den Rechten der Lernenden Rechnung tragen.",
    storyZh: "未来的规则必须同时顾及不同学校的实际情况和学习者的权利。",
  },
] satisfies readonly AdvancedWordEntry[];


export const B2_WORDS = [
  {
    id: "b2-beruecksichtigen",
    level: "B2",
    term: "berücksichtigen",
    forms: "berücksichtigen · berücksichtigt · berücksichtigte · hat berücksichtigt",
    type: "Verb",
    meaning: "考虑到；把……纳入考量",
    example: "Bei der Planung müssen wir die Bedürfnisse älterer Menschen berücksichtigen.",
    exampleZh: "规划时，我们必须考虑老年人的需求。",
    grammarTitle: "berücksichtigen + Akkusativ",
    grammar: "及物动词，宾语直接使用第四格，不与 für 连用。前缀 be- 不可分，因此完成分词不加 ge-。",
    memory: "把某个因素带进自己的视野里，就是将它纳入考虑。",
    storyDe: "Die Stadt wollte den alten Bahnhof neu gestalten und dabei die Wünsche der Anwohner berücksichtigen.",
    storyZh: "市政府想重新改造旧车站，同时把附近居民的意见纳入考虑。",
  },
  {
    id: "b2-voraussetzung",
    level: "B2",
    term: "die Voraussetzung",
    forms: "die Voraussetzung · die Voraussetzungen",
    type: "Nomen · feminin",
    meaning: "前提；先决条件",
    example: "Gute Sprachkenntnisse sind eine wichtige Voraussetzung für diese Stelle.",
    exampleZh: "良好的语言能力是这份工作的一项重要前提。",
    grammarTitle: "Voraussetzung für + Akkusativ",
    grammar: "常用 eine Voraussetzung für etw.；也可使用 unter der Voraussetzung, dass ... 表示“条件是……”。",
    memory: "voraus 表示“在前面”，某件事必须先存在，才构成 Voraussetzung。",
    storyDe: "Eine zentrale Voraussetzung dafür war allerdings, dass das Projekt finanzierbar blieb.",
    storyZh: "不过，一个关键前提是这个项目必须保持在可负担的预算范围内。",
  },
  {
    id: "b2-auseinandersetzen",
    level: "B2",
    term: "sich auseinandersetzen",
    forms: "setzt sich auseinander · setzte sich auseinander · hat sich auseinandergesetzt",
    type: "Reflexives Verb",
    meaning: "深入探讨；认真应对",
    example: "Im Seminar setzen wir uns mit den Folgen des Klimawandels auseinander.",
    exampleZh: "研讨课上，我们深入探讨气候变化带来的后果。",
    grammarTitle: "sich mit + Dativ auseinandersetzen",
    grammar: "反身动词，mit 后接第三格。现在时前缀 auseinander 分离，完成时写作 auseinandergesetzt。",
    memory: "把复杂问题拆开来看，再认真处理各个部分。",
    storyDe: "In mehreren Treffen setzten sich Fachleute und Bewohner mit unterschiedlichen Entwürfen auseinander.",
    storyZh: "在几次会议中，专家和居民认真讨论了不同的设计方案。",
  },
  {
    id: "b2-nachvollziehbar",
    level: "B2",
    term: "nachvollziehbar",
    forms: "nachvollziehbar · nachvollziehbarer · am nachvollziehbarsten",
    type: "Adjektiv",
    meaning: "可以理解的；有据可循的",
    example: "Ihre Entscheidung ist aus wirtschaftlicher Sicht nachvollziehbar.",
    exampleZh: "从经济角度看，她的决定是可以理解的。",
    grammarTitle: "nachvollziehbar sein",
    grammar: "常作表语：etw. ist nachvollziehbar。可与 für + Akkusativ 或 aus ... Sicht 搭配；作定语时添加词尾。",
    memory: "沿着对方的思路再走一遍，能走通便说明 nachvollziehbar。",
    storyDe: "Der bevorzugte Vorschlag war nachvollziehbar begründet und ließ Raum für Anpassungen.",
    storyZh: "最受青睐的方案论证清楚，也为后续调整留出了空间。",
  },
  {
    id: "b2-zusammenhang",
    level: "B2",
    term: "der Zusammenhang",
    forms: "der Zusammenhang · die Zusammenhänge",
    type: "Nomen · maskulin",
    meaning: "联系；关联；上下文",
    example: "Zwischen regelmäßigem Schlaf und guter Konzentration besteht ein deutlicher Zusammenhang.",
    exampleZh: "规律睡眠与良好专注力之间存在明显联系。",
    grammarTitle: "Zusammenhang zwischen / mit",
    grammar: "zwischen A und B 后两项使用第三格；im Zusammenhang mit + Dativ 表示“与……有关”。",
    memory: "zusammen 是“一起”，hängen 是“挂着”：两件事挂在一起，就产生联系。",
    storyDe: "Besonders wichtig war der Zusammenhang zwischen einer guten Verkehrsanbindung und hoher Lebensqualität.",
    storyZh: "其中，便利的交通连接与较高生活质量之间的关系尤其重要。",
  },
  {
    id: "b2-ueberwiegend",
    level: "B2",
    term: "überwiegend",
    forms: "überwiegend · als Adverb unverändert",
    type: "Adverb / Adjektiv",
    meaning: "主要地；绝大部分地",
    example: "Die Rückmeldungen der Teilnehmenden waren überwiegend positiv.",
    exampleZh: "参与者的反馈大多是积极的。",
    grammarTitle: "副词与形容词用法",
    grammar: "作副词时形式不变；作定语形容词时需要词尾变化，例如 die überwiegende Mehrheit。",
    memory: "wiegen 是“称重”；某一部分更重，便是占主要部分。",
    storyDe: "Die Rückmeldungen aus dem Viertel fielen überwiegend positiv aus.",
    storyZh: "来自该街区的反馈总体上是积极的。",
  },
  {
    id: "b2-bewaeltigen",
    level: "B2",
    term: "bewältigen",
    forms: "bewältigen · bewältigt · bewältigte · hat bewältigt",
    type: "Verb",
    meaning: "应对并完成；克服",
    example: "Mit einem klaren Plan lässt sich die zusätzliche Arbeit gut bewältigen.",
    exampleZh: "有了清晰的计划，额外的工作就能得到妥善处理。",
    grammarTitle: "bewältigen + Akkusativ",
    grammar: "及物动词，常与 Aufgabe、Krise、Problem 或 Herausforderung 搭配。be- 不可分，完成分词不加 ge-。",
    memory: "不是暂时忍受困难，而是把它真正处理完、克服掉。",
    storyDe: "Trotzdem musste das Team noch technische und finanzielle Schwierigkeiten bewältigen.",
    storyZh: "尽管如此，团队仍须克服技术和资金方面的困难。",
  },
  {
    id: "b2-auswirkung",
    level: "B2",
    term: "die Auswirkung",
    forms: "die Auswirkung · die Auswirkungen",
    type: "Nomen · feminin",
    meaning: "影响；后果",
    example: "Die neue Regelung hat direkte Auswirkungen auf kleine Betriebe.",
    exampleZh: "这项新规定会直接影响小型企业。",
    grammarTitle: "Auswirkung auf + Akkusativ",
    grammar: "实际使用中常见复数 Auswirkungen；auf 后接第四格。对应动词是 sich auf etw. auswirken。",
    memory: "某件事向外产生作用，就是它带来的 Auswirkung。",
    storyDe: "Am Ende prüfte der Stadtrat sorgfältig, welche langfristigen Auswirkungen der Umbau haben würde.",
    storyZh: "最后，市议会认真评估了这次改造可能产生的长期影响。",
  },
  {
    id: "b2-entwurf",
    level: "B2",
    term: "der Entwurf",
    forms: "der Entwurf · die Entwürfe",
    type: "Nomen · maskulin",
    meaning: "草案；设计稿；初步方案",
    example: "Der Ausschuss legte einen überarbeiteten Entwurf für das Verkehrskonzept vor.",
    exampleZh: "委员会提交了一份经过修改的交通方案草案。",
    grammarTitle: "Entwurf für + Akkusativ",
    grammar: "常与 für + Akkusativ 搭配。对应动词 entwerfen：entwirft · entwarf · hat entworfen。",
    memory: "Entwurf 是尚可修改的初步版本，还不是最终定案。",
    storyDe: "Nach langer Beratung legte die Arbeitsgruppe schließlich einen endgültigen Entwurf vor.",
    storyZh: "经过长时间讨论，工作组终于提交了最终设计方案。",
  },
  {
    id: "b2-zustimmen",
    level: "B2",
    term: "zustimmen",
    forms: "stimmt zu · stimmte zu · hat zugestimmt",
    type: "Verb · trennbar",
    meaning: "赞同；同意",
    example: "Die Mehrheit der Mitglieder stimmte dem Vorschlag zu.",
    exampleZh: "大多数成员赞同这项提议。",
    grammarTitle: "jdm. / etw. zustimmen",
    grammar: "zustimmen 支配第三格：Ich stimme dir / dem Plan zu。前缀 zu- 可分，完成分词为 zugestimmt。",
    memory: "把自己的声音加到某人或某项方案上，就是表示赞同。",
    storyDe: "Eine deutliche Mehrheit des Stadtrats stimmte diesem Entwurf zu.",
    storyZh: "市议会中明显过半的成员赞同了这份方案。",
  },
  {
    id: "b2-einwand",
    level: "B2",
    term: "der Einwand",
    forms: "der Einwand · die Einwände",
    type: "Nomen · maskulin",
    meaning: "异议；反对理由",
    example: "Gegen die vorgeschlagene Finanzierung wurden mehrere Einwände erhoben.",
    exampleZh: "针对提议的融资方式，人们提出了多项异议。",
    grammarTitle: "Einwand gegen + Akkusativ",
    grammar: "常用 einen Einwand erheben、vorbringen 或 haben；gegen 后接第四格。注意复数变音：Einwände。",
    memory: "Einwand 不是简单说“不”，而是提出一个需要认真回应的反对理由。",
    storyDe: "Die verbleibenden Einwände wurden dokumentiert und bei der weiteren Planung berücksichtigt.",
    storyZh: "剩余的异议被记录下来，并纳入后续规划。",
  },
  {
    id: "b2-umsetzen",
    level: "B2",
    term: "umsetzen",
    forms: "setzt um · setzte um · hat umgesetzt",
    type: "Verb · trennbar",
    meaning: "落实；实施；转化为行动",
    example: "Das Unternehmen will die neuen Sicherheitsregeln schrittweise umsetzen.",
    exampleZh: "公司计划逐步落实新的安全规定。",
    grammarTitle: "etw. in die Praxis umsetzen",
    grammar: "表示“实施”时是可分动词并支配第四格；常用 einen Plan、eine Idee 或 eine Maßnahme umsetzen。",
    memory: "把纸面上的想法搬到现实中，就是 umsetzen。",
    storyDe: "Anschließend sollte das Vorhaben in mehreren überschaubaren Bauabschnitten umgesetzt werden.",
    storyZh: "随后，这项计划将分成几个规模可控的施工阶段加以实施。",
  },
  {
    id: "b2-aufwand",
    level: "B2",
    term: "der Aufwand",
    forms: "der Aufwand · meist im Singular",
    type: "Nomen · maskulin",
    meaning: "投入；耗费；工作量",
    example: "Der organisatorische Aufwand war größer als zunächst erwartet.",
    exampleZh: "组织协调方面的投入比最初预计的更大。",
    grammarTitle: "Aufwand für / mit",
    grammar: "常用 der Aufwand für + Akkusativ、mit großem Aufwand 或 viel Zeit und Aufwand。泛指总体投入时通常用单数。",
    memory: "完成一件事必须花掉的时间、精力和资源，合起来就是 Aufwand。",
    storyDe: "Der organisatorische Aufwand war beträchtlich, blieb dank einer klaren Aufgabenverteilung aber beherrschbar.",
    storyZh: "组织协调的工作量相当大，但由于分工清楚，仍在可控范围内。",
  },
  {
    id: "b2-gewaehrleisten",
    level: "B2",
    term: "gewährleisten",
    forms: "gewährleisten · gewährleistet · gewährleistete · hat gewährleistet",
    type: "Verb",
    meaning: "确保；保障",
    example: "Regelmäßige Kontrollen sollen die Qualität der Lebensmittel gewährleisten.",
    exampleZh: "定期检查旨在确保食品质量。",
    grammarTitle: "etw. gewährleisten",
    grammar: "及物动词，直接接第四格；也可接 dass 从句。前缀 ge- 属于词干，完成分词仍是 gewährleistet。",
    memory: "它比简单的 sicherstellen 更正式，常用于制度、质量和安全保障。",
    storyDe: "Regelmäßige Kontrollen sollten gewährleisten, dass Kosten und Zeitplan eingehalten wurden.",
    storyZh: "定期检查用于确保项目遵守预算和时间安排。",
  },
  {
    id: "b2-zugang",
    level: "B2",
    term: "der Zugang",
    forms: "der Zugang · die Zugänge",
    type: "Nomen · maskulin",
    meaning: "入口；使用或接触某物的机会",
    example: "Alle Kinder sollten Zugang zu guter Bildung haben.",
    exampleZh: "所有儿童都应有机会接受良好教育。",
    grammarTitle: "Zugang zu + Dativ",
    grammar: "无论表示实体入口还是抽象使用机会，zu 后都接第三格：Zugang zum Gebäude / zu Informationen。",
    memory: "zu 加 Gang：一条通向某处或某种资源的道路。",
    storyDe: "Besonderer Wert wurde auf einen barrierefreien Zugang zu Bahnsteigen und Geschäften gelegt.",
    storyZh: "规划尤其重视让人们能够无障碍进入站台和商店。",
  },
  {
    id: "b2-langfristig",
    level: "B2",
    term: "langfristig",
    forms: "langfristig · langfristiger · am langfristigsten",
    type: "Adjektiv / Adverb",
    meaning: "长期的；从长远来看",
    example: "Die Investition soll die Betriebskosten langfristig senken.",
    exampleZh: "这项投资旨在长期降低运营成本。",
    grammarTitle: "形容词与副词用法",
    grammar: "作副词时形式不变：langfristig planen；作定语时添加词尾：eine langfristige Lösung。",
    memory: "Frist 是期限；跨越较长期限来看，就是 langfristig。",
    storyDe: "Langfristig sollte der Bahnhof nicht nur funktionaler, sondern auch zu einem lebendigen Treffpunkt werden.",
    storyZh: "从长远来看，车站不仅要更加实用，也要成为一个充满活力的公共空间。",
  },
  {
    id: "b2-beteiligen",
    level: "B2",
    term: "sich beteiligen",
    forms: "beteiligt sich · beteiligte sich · hat sich beteiligt",
    type: "Reflexives Verb",
    meaning: "参与；加入",
    example: "Viele Jugendliche beteiligten sich an der öffentlichen Diskussion.",
    exampleZh: "许多年轻人参与了公开讨论。",
    grammarTitle: "sich an + Dativ beteiligen",
    grammar: "反身代词随主语变化，an 后使用第三格：Sie beteiligt sich an dem Projekt / am Projekt。",
    memory: "Teil 是“部分”；让自己成为整体的一部分，就是参与。",
    storyDe: "Auch während der Bauphase konnten sich die Bewohner an regelmäßigen Gesprächen beteiligen.",
    storyZh: "即使在施工期间，居民也可以继续参与定期交流。",
  },
  {
    id: "b2-ruecksichtnahme",
    level: "B2",
    term: "die Rücksichtnahme",
    forms: "die Rücksichtnahme · meist im Singular",
    type: "Nomen · feminin",
    meaning: "体谅；顾及他人",
    example: "Das Zusammenleben erfordert gegenseitige Rücksichtnahme.",
    exampleZh: "共同生活需要彼此体谅。",
    grammarTitle: "Rücksichtnahme auf + Akkusativ",
    grammar: "常用 Rücksichtnahme auf jdn. / etw.；也常见 unter Rücksichtnahme auf。通常作为不可数名词使用。",
    memory: "行动前回头看一眼别人会受到什么影响，就是 Rücksichtnahme。",
    storyDe: "Die Arbeiten erfolgten unter besonderer Rücksichtnahme auf ältere Anwohner und örtliche Geschäfte.",
    storyZh: "施工过程中尤其顾及了年长居民和当地商铺。",
  },
  {
    id: "b2-entscheidend",
    level: "B2",
    term: "entscheidend",
    forms: "entscheidend · entscheidender · am entscheidendsten",
    type: "Adjektiv / Adverb",
    meaning: "决定性的；至关重要的",
    example: "Eine offene Kommunikation war für den Erfolg des Projekts entscheidend.",
    exampleZh: "开放的沟通对项目成功至关重要。",
    grammarTitle: "entscheidend für + Akkusativ",
    grammar: "常用 entscheidend für etw. sein；接从句时可说 entscheidend dafür sein, dass ...。",
    memory: "它不只是“重要”，而是足以影响最终结果。",
    storyDe: "Für die Akzeptanz des Projekts erwies sich eine offene Kommunikation als entscheidend.",
    storyZh: "事实证明，公开透明的沟通是项目获得认可的关键。",
  },
  {
    id: "b2-bewaehren",
    level: "B2",
    term: "sich bewähren",
    forms: "bewährt sich · bewährte sich · hat sich bewährt",
    type: "Reflexives Verb",
    meaning: "经受住考验；证明行之有效",
    example: "Die neue Arbeitsweise hat sich im Alltag bereits bewährt.",
    exampleZh: "这种新的工作方式已经在日常实践中证明有效。",
    grammarTitle: "sich in der Praxis bewähren",
    grammar: "常与 in + Dativ 搭配，表示某人或某物经过实际检验后证明可靠、有效。",
    memory: "不是理论上看起来不错，而是真正用过之后仍然可靠。",
    storyDe: "Schon wenige Monate nach der Eröffnung bewährte sich der neue Bahnhof im täglichen Betrieb.",
    storyZh: "开放仅几个月后，新车站就在日常运营中证明了它的实用性。",
  },
] satisfies readonly AdvancedWordEntry[];
